### ISSUE TITLE
CUDA out of memory while trying to quantize galactica-30b 

### ISSUE THREAD

**Issue by oobabooga** [qwopqwop200/GPTQ-for-LLaMa#110]
With this command in the triton branch:

> CUDA_VISIBLE_DEVICES=0 python -u opt.py ~/models/facebook_galactica-30b c4 --wbits 4 --true-sequential --act-order --groupsize 128 --save galactica-30b-int4-128g.pt | tee galactica-001.log

I get an out of memory error after 8/48 layers:

```
Quantizing fc2 in layer 8/48...
Traceback (most recent call last):
  File "/home/me/repositories/GPTQ-for-LLaMa/opt.py", line 469, in <module>
    quantizers = opt_sequential(model, dataloader, DEV)
  File "/home/me/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/me/repositories/GPTQ-for-LLaMa/opt.py", line 115, in opt_sequential
    scale,zero,g_idx = gptq[name].fasterquant(percdamp=args.percdamp, groupsize=args.groupsize, actorder=args.act_order)
  File "/home/me/repositories/GPTQ-for-LLaMa/gptq.py", line 92, in fasterquant
    H = torch.cholesky_inverse(H)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.06 GiB (GPU 0; 23.68 GiB total capacity; 16.88 GiB already allocated; 2.75 GiB free; 20.48 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

In the cuda branch, the quantization goes to the end but the model can't be saved due to an error in `opt_pack`.

#### System info

Linux Mint
RTX 3090

**Comment by oobabooga** [comment]
I have added this change to `opt.py` in the CUDA branch:

```diff
 # TODO: perform packing on GPU
 def opt_pack(model, quantizers, wbits, groupsize):
     layers = find_layers(model)
+    for n in quantizers:
+        print("===", n, n in layers)
     layers = {n: layers[n] for n in quantizers}
     make_quant(model, quantizers, wbits, groupsize)
     qlayers = find_layers(model, [QuantLinear])
```

This is what was printed at the end of quantization when `opt_pack` was called. It seems like no layer in `quantizers` is present in `find_layers(model)`.

```
=== model.layers.0.self_attn.k_proj False
=== model.layers.0.self_attn.v_proj False
=== model.layers.0.self_attn.q_proj False
=== model.layers.0.self_attn.out_proj False
=== model.layers.0.fc1 False
=== model.layers.0.fc2 False
=== model.layers.1.self_attn.k_proj False
=== model.layers.1.self_attn.v_proj False
=== model.layers.1.self_attn.q_proj False
=== model.layers.1.self_attn.out_proj False
=== model.layers.1.fc1 False
=== model.layers.1.fc2 False
=== model.layers.2.self_attn.k_proj False
=== model.layers.2.self_attn.v_proj False
=== model.layers.2.self_attn.q_proj False
=== model.layers.2.self_attn.out_proj False
=== model.layers.2.fc1 False
=== model.layers.2.fc2 False
=== model.layers.3.self_attn.k_proj False
=== model.layers.3.self_attn.v_proj False
=== model.layers.3.self_attn.q_proj False
=== model.layers.3.self_attn.out_proj False
=== model.layers.3.fc1 False
=== model.layers.3.fc2 False
=== model.layers.4.self_attn.k_proj False
```

@qwopqwop200

**Comment by RandomInternetPreson** [comment]
Frick...I'm trying to quantize that model too!!

**Comment by oobabooga** [comment]
Did you get the same error?

**Comment by RandomInternetPreson** [comment]
Yup! I'm running it on your one-click Windows install from git pull 1445ea86. On a 4090 I get this:

```
10 fc2
Quantizing ...
Traceback (most recent call last):
  File "F:\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa\opt.py", line 473, in <module>
    quantizers = opt_sequential(model, dataloader, DEV)
  File "F:\oobabooga-windows\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa\opt.py", line 116, in opt_sequential
    scale,zero = gptq[name].fasterquant(percdamp=args.percdamp, groupsize=args.groupsize, actorder=args.act_order)
  File "F:\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa\gptq.py", line 92, in fasterquant
    H = torch.cholesky_inverse(H)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.06 GiB (GPU 0; 23.99 GiB total capacity; 16.99 GiB already allocated; 1.94 GiB free; 20.28 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Press any key to continue . . .
```

I'm just editing the start-webui.bat file with the command below, and changing the startup directory.

`call python opt.py F:\oobabooga-windows\text-generation-webui\models\galactica-30b c4 --wbits 4 --true-sequential --act-order --groupsize 128 --save galactica-30b-int4-128g.pt`

Would be cool to be able to run this model in 4bit mode.  I saw a post a while ago where you were trying to do this, and I've been trying to do it myself.

**Comment by RandomInternetPreson** [comment]
I tried ptb instead of c4 to see if that made any difference, and I got the same error.

**Comment by oobabooga** [comment]
I am going to use a past commit of the `cuda` branch in the web UI for now (`a6f363e3f93b9fb5c26064b5ac7ed58d22e3f773`)

```console
# activate the conda environment
conda activate textgen

# remove the existing GPT-for-LLaMa
cd text-generation-webui/repositories
rm -rf GPTQ-for-LLaMa
pip uninstall quant-cuda

# reinstall
git clone https://github.com/oobabooga/GPTQ-for-LLaMa.git -b cuda
cd GPTQ-for-LLaMa
python setup_cuda.py install
```

In this commit, I can run the quantization but not save the model.

**Comment by qwopqwop200** [comment]
Confirmed the same issue. But first I have identified an issue where currently OPT is working but galactica is not.

**Comment by oobabooga** [comment]
By the way, quantizing with https://github.com/IST-DASLab/gptq works and the quantized model is saved, so I am assuming the fix is probably a one line change somewhere in `opt.py`.

**Comment by qwopqwop200** [comment]
At least in 30B, the OOM problem was solved. However, this should still solve the problem of the PPL coming out very high.
https://github.com/qwopqwop200/GPTQ-for-LLaMa/issues/46

**Comment by RandomInternetPreson** [comment]
> I am going to use a past commit of the `cuda` branch in the web UI for now (`a6f363e3f93b9fb5c26064b5ac7ed58d22e3f773`)
> 
> ```
> # activate the conda environment
> conda activate textgen
> 
> # remove the existing GPT-for-LLaMa
> cd text-generation-webui/repositories
> rm -rf GPTQ-for-LLaMa
> pip uninstall quant-cuda
> 
> # reinstall
> git clone https://github.com/oobabooga/GPTQ-for-LLaMa.git -b cuda
> cd GPTQ-for-LLaMa
> python setup_cuda.py install
> ```
> 
> In this commit, I can run the quantization but not save the model.

I was able to reproduce this (I'm using the latest windows one click install).  I also tried using the latest version of gptq-for-LLaMa instead of the oobabooga repo (by altering the installation file), and trinity couldn't install. So I tried running the opt.py file without the --true-sequential command.

The opt.py file would run, but I eventually got the same oom error as before.

**Comment by official-elinas** [comment]
I'm having the same issue with OPT-30b-Erebus, though I'm just getting "Killed" without any stack trace. Happens at 2/40 at `fc2` for me. Using WSL2 Ubuntu.

**Comment by qwopqwop200** [comment]
> I'm having the same issue with OPT-30b-Erebus, though I'm just getting "Killed" without any stack trace. Happens at 2/40 at `fc2` for me. Using WSL2 Ubuntu.

Out of CPU memory. One way is to use swap memory and run it in windows. Use this [brunch](https://github.com/qwopqwop200/GPTQ-for-LLaMa/tree/cuda). After conversion, run the model in wsl2.
Or setting swap memory in WSL2.

**Comment by official-elinas** [comment]
> Out of CPU memory. 

I have 96GB of RAM. It didn't go above mid 50s in the quantization process. I'm also using the cuda branch in WSL2. I will try it in Windows itself and see if that works...

**Comment by official-elinas** [comment]
Right. This is why I tried WSL2 over Windows, since I kept getting this error with all models using the same command format I have in the past:

```
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████| 74/74 [01:55<00:00,  1.56s/it]
Traceback (most recent call last):
  File "G:\llm-webui\text-generation-webui\repositories\GPTQ-for-LLaMa\opt.py", line 451, in <module>
    dataloader, testloader = get_loaders(
  File "G:\llm-webui\text-generation-webui\repositories\GPTQ-for-LLaMa\datautils.py", line 175, in get_loaders
    return get_c4(nsamples, seed, seqlen, model)
  File "G:\llm-webui\text-generation-webui\repositories\GPTQ-for-LLaMa\datautils.py", line 56, in get_c4
    traindata = load_dataset(
  File "G:\llm-webui\installer_files\env\lib\site-packages\datasets\load.py", line 1759, in load_dataset
    builder_instance = load_dataset_builder(
  File "G:\llm-webui\installer_files\env\lib\site-packages\datasets\load.py", line 1496, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "G:\llm-webui\installer_files\env\lib\site-packages\datasets\load.py", line 1218, in dataset_module_factory
    raise e1 from None
  File "G:\llm-webui\installer_files\env\lib\site-packages\datasets\load.py", line 1202, in dataset_module_factory
    ).get_module()
  File "G:\llm-webui\installer_files\env\lib\site-packages\datasets\load.py", line 812, in get_module
    dataset_infos_path = cached_path(
  File "G:\llm-webui\installer_files\env\lib\site-packages\datasets\utils\file_utils.py", line 182, in cached_path
    output_path = get_from_cache(
  File "G:\llm-webui\installer_files\env\lib\site-packages\datasets\utils\file_utils.py", line 443, in get_from_cache
    os.makedirs(cache_dir, exist_ok=True)
  File "G:\llm-webui\installer_files\env\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "G:\llm-webui\installer_files\env\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "G:\llm-webui\installer_files\env\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"G:'
```

I am on the latest commit for the `cuda` branch and running the following command: `python opt.py "G:\models\OPT-30B-Erebus-Shard" c4 --new-eval --wbits 4 --act-order --save_safetensors erebus-30b-4bit.safetensors` (which has always worked no problem)

Also, it complains about the volume label syntax for "G" even if I call the model from another drive. 

Edit: Currently running on WSL on the triton branch with more memory allocated. Will see if it works. But executing it from Windows still is an issue.

Edit2 - Failed after it said "Done" during packing.
```
Done.
Traceback (most recent call last):
  File "/mnt/g/llm-webui/text-generation-webui/repositories/GPTQ-for-LLaMa/opt.py", line 491, in <module>
    safe_save(model.state_dict(), args.save_safetensors)
  File "/home/elinas/dev/llm-webui/venv/lib/python3.10/site-packages/safetensors/torch.py", line 72, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
  File "/home/elinas/dev/llm-webui/venv/lib/python3.10/site-packages/safetensors/torch.py", line 233, in _flatten
    raise RuntimeError(
RuntimeError: Some tensors share memory, this will lead to duplicate memory on disk and potential differences when loading them again: [{'lm_head.weight', 'model.decoder.embed_tokens.weight'}]
```
